/* ============================================================
   MindScape — content data
   ============================================================ */

const TOPICS = [
  { icon: "🧠", name: "Cognitive Psychology", desc: "How we perceive, think, remember, and solve problems — the mental machinery of the mind." },
  { icon: "❤️", name: "Social Psychology", desc: "How thoughts, feelings and behavior are shaped by the real or imagined presence of others." },
  { icon: "🧬", name: "Biological Psychology", desc: "The links between the brain, nervous system, genetics, hormones and behavior." },
  { icon: "👶", name: "Developmental Psychology", desc: "How humans grow and change across the lifespan, from infancy to old age." },
  { icon: "🩺", name: "Clinical Psychology", desc: "Assessment, diagnosis and treatment of mental health disorders and distress." },
  { icon: "👥", name: "Personality Psychology", desc: "The stable patterns of thought, emotion and behavior that make each person unique." },
  { icon: "🔬", name: "Research Methods", desc: "The scientific tools used to design studies and draw valid conclusions about behavior." },
  { icon: "📊", name: "Psychological Statistics", desc: "Turning data into insight — measuring, comparing and testing psychological hypotheses." },
];

const BRAIN_REGIONS = [
  { id: "frontal", name: "Prefrontal Cortex", color: "#38bdf8",
    fn: "Decision-making, planning, attention and impulse control. The seat of executive function and personality." },
  { id: "parietal", name: "Parietal Lobe", color: "#4f9dff",
    fn: "Processes touch, spatial awareness and the integration of sensory information into a body map." },
  { id: "temporal", name: "Temporal Lobe", color: "#6366f1",
    fn: "Home of hearing, language comprehension and — via the hippocampus — the formation of long-term memory." },
  { id: "occipital", name: "Occipital Lobe", color: "#818cf8",
    fn: "The visual cortex. Interprets color, motion, shape and depth from the eyes into what we 'see'." },
  { id: "cerebellum", name: "Cerebellum", color: "#22d3ee",
    fn: "Coordinates movement, balance and posture, and fine-tunes motor learning and timing." },
  { id: "brainstem", name: "Brainstem", color: "#0ea5e9",
    fn: "Regulates the basics of life: breathing, heart rate, sleep-wake cycles and arousal." },
  { id: "limbic", name: "Limbic System", color: "#a5b4fc",
    fn: "The emotional core — the amygdala and hippocampus drive fear, reward, motivation and memory." },
];

const CONCEPTS = [
  { emoji: "💾", name: "Memory", tag: "Cognition",
    def: "The processes by which information is encoded, stored and later retrieved.",
    theories: ["Multi-store model (Atkinson & Shiffrin)", "Working memory model (Baddeley & Hitch)", "Levels of processing"],
    example: "Recalling your childhood phone number decades later, while forgetting where you left your keys this morning.",
    people: ["Hermann Ebbinghaus", "Elizabeth Loftus"], related: ["Attention", "Learning"] },
  { emoji: "🎯", name: "Attention", tag: "Cognition",
    def: "The selective concentration of mental resources on one stimulus while ignoring others.",
    theories: ["Broadbent's filter model", "Treisman's attenuation theory", "Spotlight model"],
    example: "Hearing your own name across a noisy party — the 'cocktail party effect'.",
    people: ["Donald Broadbent", "Anne Treisman"], related: ["Memory", "Perception"] },
  { emoji: "🔥", name: "Emotion", tag: "Affect",
    def: "Complex reactions involving physiological arousal, expressive behavior and conscious feeling.",
    theories: ["James-Lange theory", "Cannon-Bard theory", "Schachter-Singer two-factor theory"],
    example: "Your heart races and you interpret that arousal as fear when a dog lunges toward you.",
    people: ["William James", "Paul Ekman"], related: ["Motivation", "Behavior"] },
  { emoji: "👁️", name: "Perception", tag: "Cognition",
    def: "The organization and interpretation of sensory information into meaningful experience.",
    theories: ["Gestalt principles", "Gibson's direct perception", "Gregory's constructivist view"],
    example: "Seeing a full triangle where only three notched circles exist (the Kanizsa illusion).",
    people: ["Max Wertheimer", "James Gibson"], related: ["Attention", "Consciousness"] },
  { emoji: "🚀", name: "Motivation", tag: "Affect",
    def: "The internal processes that initiate, direct and sustain goal-oriented behavior.",
    theories: ["Maslow's hierarchy of needs", "Self-determination theory", "Drive-reduction theory"],
    example: "Studying late into the night driven by the goal of mastering a subject you love.",
    people: ["Abraham Maslow", "Edward Deci"], related: ["Emotion", "Behavior"] },
  { emoji: "🎓", name: "Learning", tag: "Cognition",
    def: "A relatively permanent change in behavior or knowledge resulting from experience.",
    theories: ["Classical conditioning", "Operant conditioning", "Social learning theory"],
    example: "A child learns to say 'please' after being praised each time they do.",
    people: ["Ivan Pavlov", "B. F. Skinner"], related: ["Memory", "Behavior"] },
  { emoji: "💡", name: "Intelligence", tag: "Cognition",
    def: "The capacity to learn, reason, solve problems and adapt to new situations.",
    theories: ["Spearman's g factor", "Gardner's multiple intelligences", "Sternberg's triarchic theory"],
    example: "Adapting a familiar recipe to whatever ingredients happen to be in the fridge.",
    people: ["Charles Spearman", "Howard Gardner"], related: ["Learning", "Personality"] },
  { emoji: "🎭", name: "Personality", tag: "Individual",
    def: "The enduring pattern of thoughts, feelings and behaviors that distinguishes a person.",
    theories: ["Big Five (OCEAN)", "Psychodynamic theory", "Trait theory"],
    example: "One friend energized by a crowded party; another drained and craving quiet.",
    people: ["Gordon Allport", "Carl Jung"], related: ["Intelligence", "Behavior"] },
  { emoji: "🌌", name: "Consciousness", tag: "Mind",
    def: "Our subjective awareness of ourselves, our thoughts and our environment.",
    theories: ["Global workspace theory", "Integrated information theory", "Freudian levels of mind"],
    example: "The shift from focused wakefulness to dreaming as you fall asleep.",
    people: ["William James", "Sigmund Freud"], related: ["Perception", "Emotion"] },
  { emoji: "🕹️", name: "Behavior", tag: "Action",
    def: "Any observable action or response of an organism to internal or external stimuli.",
    theories: ["Behaviorism", "Cognitive-behavioral model", "Reinforcement theory"],
    example: "A rat pressing a lever more often after each press delivers a food pellet.",
    people: ["John B. Watson", "B. F. Skinner"], related: ["Learning", "Motivation"] },
];

const PSYCHOLOGISTS = [
  { initials: "SF", name: "Sigmund Freud", years: "1856–1939", field: "Psychoanalysis",
    contribution: "Founded psychoanalysis and the theory of the unconscious mind, dreams, and defense mechanisms.",
    grad: "linear-gradient(135deg,#38bdf8,#6366f1)" },
  { initials: "CJ", name: "Carl Jung", years: "1875–1961", field: "Analytical Psychology",
    contribution: "Introduced the collective unconscious, archetypes, and the concepts of introversion and extraversion.",
    grad: "linear-gradient(135deg,#818cf8,#22d3ee)" },
  { initials: "BS", name: "B. F. Skinner", years: "1904–1990", field: "Behaviorism",
    contribution: "Developed operant conditioning, showing how reinforcement and punishment shape behavior.",
    grad: "linear-gradient(135deg,#0ea5e9,#4f9dff)" },
  { initials: "JP", name: "Jean Piaget", years: "1896–1980", field: "Developmental",
    contribution: "Mapped the four stages of cognitive development in children through schemas and adaptation.",
    grad: "linear-gradient(135deg,#22d3ee,#6366f1)" },
  { initials: "AB", name: "Albert Bandura", years: "1925–2021", field: "Social-Cognitive",
    contribution: "Social learning theory and the Bobo doll studies — we learn by observing and imitating others.",
    grad: "linear-gradient(135deg,#4f9dff,#a5b4fc)" },
  { initials: "CR", name: "Carl Rogers", years: "1902–1987", field: "Humanistic",
    contribution: "Pioneered person-centered therapy and the idea of unconditional positive regard.",
    grad: "linear-gradient(135deg,#38bdf8,#818cf8)" },
  { initials: "AM", name: "Abraham Maslow", years: "1908–1970", field: "Humanistic",
    contribution: "Created the hierarchy of needs, culminating in self-actualization.",
    grad: "linear-gradient(135deg,#6366f1,#22d3ee)" },
  { initials: "IP", name: "Ivan Pavlov", years: "1849–1936", field: "Behaviorism",
    contribution: "Discovered classical conditioning through his experiments with salivating dogs.",
    grad: "linear-gradient(135deg,#0ea5e9,#818cf8)" },
];

const TIMELINE = [
  { year: "1879", title: "Wilhelm Wundt", text: "Opens the first psychology laboratory in Leipzig — psychology becomes a science." },
  { year: "1890s", title: "Functionalism", text: "William James studies the purpose of mental processes and how they help us adapt." },
  { year: "1900s", title: "Psychoanalysis", text: "Freud publishes on dreams and the unconscious, reshaping how we view the mind." },
  { year: "1910s–1950s", title: "Behaviorism", text: "Watson and Skinner focus psychology on observable behavior and learning." },
  { year: "1950s–60s", title: "Humanistic Psychology", text: "Rogers and Maslow emphasize free will, growth and self-actualization." },
  { year: "1950s–Present", title: "Cognitive Revolution", text: "The mind is studied as an information processor — memory, thinking and language." },
];

const STATS = [
  { value: 100, suffix: "+", label: "Psychology concepts" },
  { value: 50, suffix: "+", label: "Major psychologists" },
  { value: 10, suffix: "+", label: "Major psychological fields" },
  { value: null, symbol: "∞", label: "Questions about the human mind" },
];

const RESEARCH = [
  { name: "Experiments", desc: "Manipulate variables under controlled conditions to establish cause and effect.", diagram: "flask" },
  { name: "Case Studies", desc: "Deep, detailed investigation of a single person or group over time.", diagram: "person" },
  { name: "Surveys", desc: "Gather self-reported data from large samples using questionnaires.", diagram: "chart" },
  { name: "Observational Studies", desc: "Watch and record behavior in natural or structured settings without interfering.", diagram: "eye" },
  { name: "Correlational Research", desc: "Measure how strongly two variables relate — without implying causation.", diagram: "scatter" },
  { name: "Research Methods", desc: "The scientific framework of hypotheses, sampling, controls and peer review.", diagram: "loop" },
];

const RESOURCES = [
  { cat: "Notes", title: "Cognitive Psychology Study Notes", desc: "A concise revision pack covering memory models, attention and problem solving." },
  { cat: "Articles", title: "Why We Forget: The Science of Memory", desc: "An accessible look at the forgetting curve and how to make knowledge stick." },
  { cat: "Research", title: "The Bobo Doll Experiment Revisited", desc: "Summary and analysis of Bandura's landmark social learning study." },
  { cat: "Books", title: "Thinking, Fast and Slow — Overview", desc: "Kahneman's dual-system theory of the mind, distilled into key takeaways." },
  { cat: "Videos", title: "Neurons Explained in 8 Minutes", desc: "An animated primer on how neurons fire and communicate across synapses." },
  { cat: "Notes", title: "Developmental Stages Cheat Sheet", desc: "Piaget, Erikson and Vygotsky side by side for quick comparison." },
  { cat: "Articles", title: "The Big Five Personality Traits", desc: "What OCEAN really measures and why it dominates modern personality science." },
  { cat: "Research", title: "Classic Conditioning in Everyday Life", desc: "How Pavlovian principles explain habits, cravings and phobias." },
  { cat: "Books", title: "Man's Search for Meaning — Notes", desc: "Viktor Frankl's logotherapy and the psychology of finding purpose." },
  { cat: "Videos", title: "Inside the Anxious Brain", desc: "A visual tour of the amygdala, cortisol and the fight-or-flight response." },
  { cat: "Research", title: "Attachment Theory & Child Development", desc: "Bowlby and Ainsworth on how early bonds shape lifelong relationships." },
  { cat: "Articles", title: "Cognitive Biases You Fall For Daily", desc: "Anchoring, confirmation bias and the halo effect, explained with examples." },
];

const RESOURCE_FILTERS = ["All", "Notes", "Articles", "Research", "Books", "Videos"];

const QUIZ = [
  { q: "Who is considered the founder of psychoanalysis?",
    options: ["B. F. Skinner", "Sigmund Freud", "Jean Piaget", "Ivan Pavlov"], answer: 1,
    fact: "Freud developed psychoanalysis and the theory of the unconscious mind." },
  { q: "Classical conditioning was first demonstrated using which animals?",
    options: ["Rats", "Pigeons", "Dogs", "Monkeys"], answer: 2,
    fact: "Pavlov's dogs learned to salivate at the sound of a bell paired with food." },
  { q: "Which brain region is most associated with decision-making and impulse control?",
    options: ["Cerebellum", "Occipital lobe", "Prefrontal cortex", "Brainstem"], answer: 2,
    fact: "The prefrontal cortex governs executive functions like planning and self-control." },
  { q: "Maslow's hierarchy of needs culminates in which stage?",
    options: ["Safety", "Self-actualization", "Belonging", "Esteem"], answer: 1,
    fact: "Self-actualization is realizing one's full potential at the top of the pyramid." },
  { q: "The 'Big Five' personality model is also known by which acronym?",
    options: ["OCEAN", "SPACE", "MIND", "TRAIT"], answer: 0,
    fact: "OCEAN = Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism." },
  { q: "Which psychologist proposed the four stages of cognitive development?",
    options: ["Carl Rogers", "Jean Piaget", "Albert Bandura", "Carl Jung"], answer: 1,
    fact: "Piaget described sensorimotor, preoperational, concrete and formal operational stages." },
  { q: "The 'cocktail party effect' is an example of which cognitive process?",
    options: ["Memory", "Attention", "Perception", "Motivation"], answer: 1,
    fact: "It shows selective attention — noticing your name amid background noise." },
  { q: "Operant conditioning shapes behavior primarily through what?",
    options: ["Observation", "Reinforcement and punishment", "Free association", "Dream analysis"], answer: 1,
    fact: "Skinner showed consequences increase or decrease the likelihood of behavior." },
  { q: "Bandura's Bobo doll study demonstrated which type of learning?",
    options: ["Classical conditioning", "Observational learning", "Latent learning", "Insight learning"], answer: 1,
    fact: "Children imitated aggression they had watched an adult model perform." },
  { q: "Which theory states arousal and emotion occur simultaneously?",
    options: ["James-Lange", "Cannon-Bard", "Two-factor", "Drive-reduction"], answer: 1,
    fact: "The Cannon-Bard theory says physiological arousal and emotion happen at once." },
];
